### ISSUE TITLE
Manually input IP?

### ISSUE THREAD

**Issue by scutzi128** [jamesbarnett91/tplink-energy-monitor#11]
Hi I have devices at multiple physical locations on different network subnets. I am VPNed into each network with my server and can reach the TP link devices on each however the software only detects devices on either one network or the other. Is there anyway to manually input the device IPs so I can access devices on both networks from the same web server? Thanks!

**Comment by jamesbarnett91** [comment]
Hi, sorry for the slow reply.
There's no easy way to specify the plug IP's directly through config. But it's possible if you modify the code. You'll have to clone the project (and have NodeJs installed) and [run via NPM](https://github.com/jamesbarnett91/tplink-energy-monitor#node--npm).

Then in [device-manager.js](https://github.com/jamesbarnett91/tplink-energy-monitor/blob/master/services/device-manager.js#L7) it's possible to set the host+port of known devices which can be used in addition to the auto scan. 
e.g:

```
client.startDiscovery({
  deviceTypes: ['plug'],
  discoveryTimeout: 20000,
  devices: [
    {host:'192.168.0.5', port: 9999},
    {host:'192.168.0.6', port: 9999}
  ]
}).on('plug-new', registerPlug);
```
(The default plug port is 9999).
You can increase the log level for the `Client` which may contain more useful information.
`const client = new Client({logLevel: 'trace'});`

Hope this helps!

**Comment by scutzi128** [comment]
Thanks for the response. 

I tried following your direction but ran into some issues (I am a coding noob). I am on windows FYI.

I installed NodeJs and tested and verified it and NPM were installed. I then cloned the project and unzipped the files to my desktop. I edited the device-manager.js file as directed. 

I then tried to run the application by opening a cmd prompt in the root of the project directory and running  node app.js and I got an error. What am I doing wrong? 

Sorry for the noobish question but like I said I'm not very knowledgeable when it comes to coding. I'm sure I'm doing something stupidly wrong but hopefully you can help me out.

Thanks for the great app and the help. Here are some screenshots of what I have going.

![capture1](https://user-images.githubusercontent.com/11930971/49228591-b1114b00-f3b9-11e8-8293-a60b28e7bee1.PNG)

![capture2](https://user-images.githubusercontent.com/11930971/49228596-b40c3b80-f3b9-11e8-8e53-de5b04d5441a.PNG)

![capture3](https://user-images.githubusercontent.com/11930971/49228602-b5d5ff00-f3b9-11e8-8c7a-a65c750fcef1.PNG)
