### ISSUE TITLE
Hombridge integration (or IFTTT integration)

### ISSUE THREAD

**Issue by JimBeam1** [jamesbarnett91/tplink-energy-monitor#13]
I am looking for a possibility to integrate the HS110 (EU) in Homekit using Homebridge. The homebridge-tplink-smarthome project works fine for integration of the switch-function of the plug, but for the eu-version power monitoring does not work.

Since your project works fine for power monitoring of the eu-version, I was wondering, wether you could integrate a hombrigde-plugin or provide the data needed for power monitoring the eu-version in an extra branch of the homebridge-tplink-smarthome project?

(What I want to do is getting a push notification and switching the plug off when the power consumption is under a special level. My idea for now is to use a homekit automation for switching the plug of and switching a dummy switch on in homekit which will be the trigger of an IFTTT webhook generating the push notification. The missing part is the power monitoring in homekit, which seems to work for the us-version of the hs110.)

**Comment by jamesbarnett91** [comment]
Hey, sorry for the slow reply.
I don't really know anything about Homebridge. You're probably better off raising an issue on their repo directly. 
There seems to be discussion about your issue already [https://github.com/plasticrake/homebridge-tplink-smarthome/issues/57](https://github.com/plasticrake/homebridge-tplink-smarthome/issues/57)

Thanks

**Comment by jamesbarnett91** [comment]
Oh just realised you already commented on that issue! Good to hear its working now.
