### ISSUE TITLE
Mac package not working

### ISSUE THREAD

**Issue by TheKrowi** [jamesbarnett91/tplink-energy-monitor#15]
Hey,

Great app on Windows but I can't seem to get the mac version of the package to work. Do I need to do something special to get it to run? On Windows I just run the .exe but I'm clueless on my mac.

**Comment by jamesbarnett91** [comment]
Hi,
I'm afraid i don't actually have a mac so I've never run or tested the OSX build.
I think it should be a full executable though. If you just double click it does it just do nothing?
If that doesn't work, you might be able to rename the file with `.app` on the end. Could also try `.dmg` which I think is another OSX package type. 

The packaging is done by [https://github.com/zeit/pkg](https://github.com/zeit/pkg) but I can see any obvious documentation about what file it creates for OSX.
