### ISSUE TITLE
Change gauge max value

### ISSUE THREAD

**Issue by advanxer** [jamesbarnett91/tplink-energy-monitor#24]
First of all, thank you for this project. I'm currently monitoring low powered device(s) which is their power consumption is less than 20w. Is there anyway that I can change the max value for the realtime usage gauge? I saw the max value is set to 3000, which make my 20w usage is barely noticeable.

**Comment by jamesbarnett91** [comment]
Hi, sorry for the slow reply.

There's no way to change the gauge scale currently. 

If you're running the project directly via Node/NPM you could change the code that initialises the gauge 
by setting `dash.realtimeGauge.maxValue` to the maximum you want:

https://github.com/jamesbarnett91/tplink-energy-monitor/blob/master/public/javascripts/dash.js#L102;

The `staticZones` would need to be updated as well so they fall within your max range.

I'll look at adding some easily editable config that lets the range be set through the browser, but I don't get much time to work on this project at the moment so I'm afraid it probably wont happen anytime soon!

Thanks

**Comment by advanxer** [comment]
Thank you for the workaround, works for me 👍
