### ISSUE TITLE
Error Reading Logger Config

### ISSUE THREAD

**Issue by slvrscoobie** [jamesbarnett91/tplink-energy-monitor#25]
I am 100% not exactly sure how to use this, but Im hoping to dump the data from my HS100s running my heater and my freezer to excel or some other format for long term analysis. Ive got it up and running, but I cant figure out in macos what the proper syntax for the log file would be. I tried to drag a folder to the txt editor and it dropped in my userfolder/folder/tplink-energy-monitor/ but when i run it, i get 
Logger config file: "logger-config.json"
Error reading logger config. Reverting to defaults. { Error: ENOENT: no such file or directory, open 'logger-config.json'
That file is in the same folder as the executable, and is the one i edited.

**Comment by slvrscoobie** [comment]
ok, dumped it back to my home directory, and it seems to find the log file now.

**Comment by chrisprolsm** [comment]
Hi !
I'm not sure I understand what is "dumping is to the home directory" ... which home directory are we talking about ? the user directory ? or the directory where the exe is located ?
anyhow, I also have this issue : the logger config file is not loaded and default values are used instead.
I am using the windows package on a W10 machine.
