### ISSUE TITLE
Error running on Win10 (1803)

### ISSUE THREAD

**Issue by ContVarza** [jamesbarnett91/tplink-energy-monitor#5]
Hello and thanks for the excellent work!
Works but, 
Tried running it on Win 10 as administrator and also in Win7 compatibility mode and I get these errors:
`Found device: Camera Lights [80062910FBFD4923BAAFA9428113FA93189CE220]
Found device: Fan [8006544238C6695927A47251B927223A187284EB]
(node:22964) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): ResponseError: err_code not zero response: {"err_code":-1,"err_msg":"module not support"}
(node:22964) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:22964) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ResponseError: err_code not zero response: {"err_code":-1,"err_msg":"module not support"}
(node:22964) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): ResponseError: err_code not zero response: {"err_code":-1,"err_msg":"module not support"}`

**Comment by jamesbarnett91** [comment]
Hi, thanks for trying the project!

I think the "module not support" error is a response from the plug saying it does not support the energy monitoring API calls. 

What is the model number of your plugs? The monitoring page should show it at the bottom of the screen, or if i'ts not getting that far you can check the model number from the plug settings in the Kasa phone app.

If you have the HS100 then I don't believe that has the hardware to monitor to the energy consumption. Only the HS110 and above support this feature.

If you do have the HS110 then let me know and I'll try and take a closer look at the error.

Thanks

**Comment by ContVarza** [comment]
You are right, I also have one HS100 on the same network. Works well with HS110 plugs. Thank you!

**Comment by ballachango** [comment]
@ContVarza If you're happy, you can click 'close issue' so james doesn't have to.
